### ISSUE TITLE
window function works in version 0.9-7 not working in version 0.11-2

### ISSUE THREAD

**Issue by annaymj** [joshuaulrich/xts#312]
The `window` function works in an older version (0.9-7), but fails the new version.

```r
out.early.xts.window <- window(out.early.xts,start=1995.00)
Error in .toPOSIXct(start, indexTZ(x)) : invalid time / time based class
```

Can you share an example of work around ?

Was trying to install the old version using the following command, but runs into compilation issue

```r
require(devtools)
install_version("xts", "0.9-7","http://cran.us.r-project.org")
ERROR: compilation failed for package 'xts'
```

**Comment by ethanbsmith** [comment]
what is `1995.00` is supposed to represent?
maybe you want `out.early.xts.window <- window(out.early.xts, start=.POSIXct(1995.00))`
or `out.early.xts.window <- window(out.early.xts, start=as.POSIXct("1995-01-01"))`

**Comment by annaymj** [comment]
It's the year name. The workaround code seems working.

Thank you!

**Comment by annaymj** [comment]
Update. 1995.00 means year 1995 quarter Q1. 1996.25 (1996 Q2). Those works in the old library version.

.POSIXct(1995.00) is returning very weird result. 
> .POSIXct(1995.00)
> [1] "1970-01-01 00:33:15 UTC"

as.POSIXct("1995-01-01") is working
> as.POSIXct("1995-01-01")
> [1] "1995-01-01 UTC"
Do you have an easy method to convert 1995.00 to "1995-01-01"? 

Also do you have plan to make 1995.00 format working for the updated version?

Thanks a lot!

**Comment by joshuaulrich** [comment]
Hi @annaymj. I'll investigate the prior behavior and make sure it is not broken in the new version.

**Comment by joshuaulrich** [comment]
Hi @annaymj, can you please provide an example of the `out.early.xts` and `out.early.xts.window` objects, when run under 0.9-7? The `window.xts()` method was added in 0.11-0, so `window.zoo()` would have been dispatched in any prior version of xts.
